### PR TITLE
Create Artifactory as an Asset Management and Vulnerability process

### PR DESCRIPTION
**Pull request by jeanbenoitrochon**

### CODE REVIEW

**Review by s-laugh — CHANGES_REQUESTED** [review]
Will need to be converted to markdown.
- [ ] File type
- [ ] add headers
- [ ] add links

**Review by jeanbenoitrochon — COMMENTED** [review]
Changed format to MD

**Review by jeanbenoitrochon — COMMENTED** [review]
Changed from Bold to Headers.
Changed file name replaced spaces with _ and 
added ".md"

**Review by jeanbenoitrochon — COMMENTED** [review]
removed spaces as per build failed error msg.

**Review by s-laugh — CHANGES_REQUESTED** [review]
One last thing, you'll want to add a link in the README.md under the main header.

**Comment by jeanbenoitrochon** [comment]
> 
> 
> One last thing, you'll want to add a link in the README.md under the main header.

Do you mean here ? <https://github.com/esdc-devcop/recommendations/edit/master/README.md>
But still, I dont' know what to add...

Ok so I thinking about this more it should be added in the tools table found here : <https://github.com/esdc-devcop/recommendations/blob/master/tools/overview.md>

If you think it should still be in readme you would have to show me where cause I don't know where this fits in that file.

**Review by s-laugh — APPROVED** [review]

**Pull request merged**
